version = 1

test_patterns = [
  'test/**',
  '**/*_test.go',
]

exclude_patterns = [
  'vendor/**',
  'docs/**',
]

[[ analyzers ]]
  name = 'go'
  enabled = true
  
  [analyzers.meta]
    import_path = "github.com/sanketsaurav/ingress"
    dependencies_vendored = true 
